spring:
  application:
    name: gadget
  datasource:
    url: jdbc:postgresql://localhost:5432/gadget
    username: postgres
    password: 3011
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER

server:
  error:
    include-message: always





